[build]
builder = "nixpacks"
installCommand = "npm install"

[deploy]
startCommand = "npm run db:migrate:deploy && npm start -w server"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
